# Promise

```
let promise = new Promise(function(resolve, reject) {
  // executor (the producing code, "singer")
});
```
- new Promise에 파라미터로 넘겨지는 함수는 "executor/실행자?"이다.
- Promise가 생성되면, executor함수는 자동으로 실행된다.
- Executor는 'producing code'를 포함하며 이것은 결과를 만들어낸다.
- Promise객체의 결과는 내부 프로퍼티를 갖고있다.
    - state : 처음에는 "pending"상태이며, 나중에 "fulfilled" 혹은 "rejected"로 바뀐다.
    - result : 처음에는 "undefined"이며, 나중에 사용자에 따른 결과로 바뀐다.
- executor코드가 실행되고 나면, 다음 두개의 함수중 하나를 무조건 호출해야한다.
    - resolve(value) : executor코드의 job이 성공적으로 끝났음을 알린다.
        - state는 "fulfilled"로 바뀌며
        - result는 "value"로 바뀐다.
    - reject(error) : job 수행 중에 에러가 발생했음을 나타낸다.
        - state는  "rejected"로 바뀐다
        - result는 error이다.


```
let promise = new Promise(function(resolve, reject) {
  // the function is executed automatically when the promise is constructed

  // after 1 second signal that the job is done with the result "done!"
  setTimeout(() => resolve("done!"), 1000);
});

promise; // state: "pending", result: undefined
//after 1 second signal that the job is done with the result "done!"
promise; // state: "fulfilled", result: "done"
```
- Executor는 자동적으로 즉시 new Promise에 의해 불려진다
- Executor는 2개의 arguments인 resolve, reject를 받는다.
    - resolve, reject는 이미 자바스크립트 엔진에 pre-defined되어있다.
- executor코드에 정의된대로, 1초 후에 resolve("done")를 호출하여 결과를 produce한다.
### There can be only a single result or an error
- Executor는 오직 하나의 resolve 혹은 reject를 호출한다.
- 최초의 resolve 혹은 reject만 호출이 되며 그 후의 것들은 모두 무시된다.
### Reject with Error objects
- Reject의 경우 가급적 Error 오브젝트를 생성해서 넘기는것을 권장한다.
### Immediately calling resolve/reject
- Promise 오브젝트의 state, result 프로퍼티는 내부적인 것이다.
- 즉 direct access가 불가능하므로, .then/.catch를 통해서 접근이 가능하다.

## Consumers: “then” and “catch”
- Promise 오브젝트는 executor와 consuming functions사이의 중간 역할을 해주며, 두 함수?를 연결시켜준다.
- Promise 오브젝트에 .then / .catch 메소드를 통해 consuming functions이 등록 가능하다.
```
promise.then(
  function(result) { /* handle a successful result */ },
  function(error) { /* handle an error */ }
);
```
- .then의 첫번째 argument는 Promise가 resolve되면 실행되며 result를 받는다.
- .then의 두번쨰 argument는 Promise가 rejected되면 실행되며 error를 받는다.

```
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => resolve("done!"), 1000);
});

// resolve runs the first function in .then
promise.then(
  result => alert(result), // shows "done!" after 1 second
  error => alert(error) // doesn't run
);
```
```
let promise = new Promise(function(resolve, reject) {
  setTimeout(() => reject(new Error("Whoops!")), 1000);
});

// reject runs the second function in .then
promise.then(
  result => alert(result), // doesn't run
  error => alert(error) // shows "Error: Whoops!" after 1 second
);
```
- 만약 우리는 resolve된 result가 아니라, error에만 관심이있다면, 처음 argument를 null로 넣을 수 있다. .then(null, errorHandlingFunction)
- 혹은 .catch(errorHandlingFunction)를 사용해서 해결 가능하다.
```
let promise = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error("Whoops!")), 1000);
});

// .catch(f) is the same as promise.then(null, f)
promise.catch(alert); // shows "Error: Whoops!" after 1 second
```

## On settled promises then runs immediately
- 만약 Promise가 pending상태이면, .then/catch 핸들러는 결과를 기다린다.
- pending상태가 아니면, 즉시 실행된다.

## Handlers of .then/.catch are always asynchronous
- Promise가 즉시 resolve되고, 바로 .then/.catch를 할지라도 consumer코드가 바로 실행 안될수 도 있다.
- 자바스크립트 엔진은 내부적으로 .then/catch를 handling하는 execution queue를 갖고 있다.
- 이 내부 엔진은 오직 현재 실행중인 코드가 끝나면 읽힌다.
- 즉 현재모든 코드가 실행되어야, .then/catch 핸들러에 있는 코드들이 실행된다.
```
// an "immediately" resolved Promise
const executor = resolve => resolve("done!");
const promise = new Promise(executor);

promise.then(alert); // this alert shows last (*)

alert("code finished"); // this alert shows first
```


```

let obj = {
   array_odd : [1,3,5,7,9],
   array_even : [2,4,6,8,10]
}
function loadScript(obj, src) {
    return new Promise( function(resolve,reject){
        let script = document.createElement('script');
        script.src = src;
        script.onload = () => resolve(obj);
        script.onerror = () => reject(new Error("Script load error: " + src));
        document.head.append(script);
    });
}


let promise = loadScript(obj, 'https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.2.0/lodash.js');
promise.then(
    script => alert( _.sortBy(_.union(obj['array_odd'],obj['array_even'])) ), // function declared in the loaded script
    error => alert(`Error: ${error.message}`)
);

```


[참고 사이트](https://javascript.info/promise-basics)